---
version: '3.5'

x-dockerfile-name:
  &local-dockerfile
  build:
    dockerfile: Dockerfile.local
    cache_from:
      - cch_build

services:
  cch_build:
    depends_on: 
      - cch_tomcat
    image: cch_build
    build:
      context: .
      dockerfile: ./Docker/cch_build/Dockerfile
      target: cch_build
    command: echo

  cch_postgres:
    depends_on: 
      - cch_build
    << : *local-dockerfile

  cch_n52_wps:
    depends_on: 
      - cch_build
    << : *local-dockerfile

  cch_portal:
    depends_on: 
      - cch_build
    << : *local-dockerfile

  cch_geoserver:
    depends_on: 
      - cch_build
    << : *local-dockerfile
