---
version: '3.5'

x-dockerfile-name:
  &local-dockerfile
  build:
    dockerfile: Dockerfile.local

services:
  cch_postgres:
    << : *local-dockerfile

  cch_n52_wps:
    << : *local-dockerfile

  cch_portal:
    << : *local-dockerfile

  cch_geoserver:
    << : *local-dockerfile
