---
version: '3.5'

x-dockerfile-name:
  &local-dockerfile
  build:
    dockerfile: Dockerfile.local
    cache_from:
      - maven_base

services:
  maven_base:
    image: maven_base
    build:
      context: .
      dockerfile: ./Docker/maven_base/Dockerfile
      target: maven_base
    volumes:
      - type: bind
        source: ./
        target: /source

  cch_postgres:
    << : *local-dockerfile

  cch_n52_wps:
    << : *local-dockerfile

  cch_portal:
    << : *local-dockerfile

  cch_geoserver:
    << : *local-dockerfile
