cchrserve:
  build: ./src/main/resources/docker/rserve
  hostname: cch_rserve
  environment:
      - PASSWORD=rserve
      
cchn52:
  build: ./src/main/resources/docker/n52-wps
  hostname: cch_n52
  links:
      - cchrserve
  ports:
      - "8082:8080"