cchgeoserverdata:
    image: alpine
    volumes:
        - /heapdumps
        - /data
    command: /bin/echo 
    
cchgeoserver:
  build: ./src/main/resources/docker
  volumes_from:
    - cchgeoserverdata
  hostname: cch_geoserver
  ports:
    - "8081:8080"